apiVersion: apps/v1
kind: Deployment

metadata:
  name: demo-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: demo-app

  template:
    metadata:
      labels:
        app: demo-app

    spec:
      containers:
      - name: demo
        image: rohansujay/sample-python-app:v1

        ports:
        - containerPort: 5000
